build:
    environment:
        variables:
                APP_DEBUG: true
                APP_KEY: base64:gp5H9hu+vebVtsr7HEuLRCB10MN/4ApH+ARlmEq5urk=
                APP_TIMEZONE: "UTC"
                APP_WELCOME_MESSAGE: "LaCMS API"

                CACHE_DRIVER: file
                QUEUE_DRIVER: sync

                API_STANDARDS_TREE: "vnd"
                API_PREFIX: "api"
                API_VERSION: "v1"
                API_NAME: "LACMS API"
                API_STRICT: false
                API_DEBUG: true

filter:
    excluded_paths: [tests/*]

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    external_code_coverage:
        timeout: 600

